/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "StripLights.h"
#include "StripLights_fonts.h"
#include "S0.h"
#include "S0_aliases.h"
#include "SW1.h"
#include "SW1_aliases.h"
#include "SPIS.h"
#include "SPIS_SPI_UART.h"
#include "SPIS_PINS.h"
#include "SPIS_SPI_UART_PVT.h"
#include "SPIS_PVT.h"
#include "SPIS_BOOT.h"
#include "StripLights_HFCLK.h"
#include "StripLights_cisr.h"
#include "StripLights_fisr.h"
#include "StripLights_StringSel.h"
#include "SPIS_SCBCLK.h"
#include "SPIS_ss_s.h"
#include "SPIS_ss_s_aliases.h"
#include "SPIS_miso_s.h"
#include "SPIS_miso_s_aliases.h"
#include "SPIS_sclk_s.h"
#include "SPIS_sclk_s_aliases.h"
#include "SPIS_mosi_s.h"
#include "SPIS_mosi_s_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"

/*[]*/

